language: java
os:
  - linux
  - osx
jdk:
  - openjdk9

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get -y install cmake libssl-dev maven; fi
  - git submodule update --init --recursive
  - rm -rf target/
  - make

install: /bin/true
